putraApp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\bookController;
use App\Http\Controllers\pinjamController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\pengembalianController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/dashboard', function () {
    return view('index');
});


Route::resource('books', bookController::class);

Route::resource('members', memberController::class);

Route::resource('pinjams',pinjamController::class);

Route::resource('pengembalians', pengembalianController::class);

Route::resource('posts', PostController::class);

putraApp/app/Models/pinjam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class pinjam extends Model
{
    use HasFactory;
    protected $fillable = ['kode_pinjam','nama_anggota','tanggal_pinjam','tanggal_kembali'];
}

putraApp/app/Http/Controllers/pinjamController.php
<?php

namespace App\Http\Controllers;

use App\Models\pinjam;
use Illuminate\Http\Request;

class pinjamController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pinjams = pinjam::all();
        return view('pinjams.index', ['pinjams' => $pinjams]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('pinjams.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'kode_pinjam' => 'required',
            'nama_anggota' => 'required',
            'tanggal_pinjam' => 'required',
            'tanggal_kembali' => 'required',
        ]);

        //simpan ke database
        $pinjam = pinjam::create([
            'kode_pinjam' => $request->input ('kode_pinjam'),
            'nama_anggota' => $request->input ('nama_anggota'),
            'tanggal_pinjam' => $request->input ('tanggal_pinjam'),
            'tanggal_kembali' => $request->input ('tanggal_kembali'),
        ]);

        //flash message
        if($pinjam){
            return redirect()->route('pinjams.index')->with('success','Data Berhasil Disimpan');
        }
        else{
            return redirect()->back()->with('error','Data Gagal Disimpan');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(pinjam $pinjam)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $pinjam = pinjam::find($id);
        return view('pinjams.edit', ['pinjam' => $pinjam]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, pinjam $pinjam)
    {
        $validated = $request->validate([
            'kode_pinjam' => 'required',
            'nama_anggota' => 'required',
            'tanggal_pinjam' => 'required',
            'tanggal_kembali' => 'required',
        ]);

        //simpan ke database
        $pinjam->update([
            'kode_pinjam' => $request->input ('kode_pinjam'),
            'nama_anggota' => $request->input ('nama_anggota'),
            'tanggal_pinjam' => $request->input ('tanggal_pinjam'),
            'tanggal_kembali' => $request->input ('tanggal_kembali'),
        ]);

        //flash message
        if($pinjam){
            return redirect()->route('pinjams.index')->with('success','Data Berhasil Diperbaruhi');
        }
        else{
            return redirect()->back()->with('error','Data Gagal Diperbaruhi');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $pinjams = pinjam::destroy($id);
        $pinjams = pinjam::all();
        return view('pinjams.index', ['pinjams' => $pinjams]);
    }
}

putraApp/resources/views/pinjams/create.blade.php
@include('layout/header', ['title' => 'Form Data Peminjaman']) 
    <div class="container pt-4 bg-white">
    <h2>Form Peminjaman Buku</h2>
    @if ($errors->any()) 
            <div class="alert alert-danger"> 
                <ul> 
                    @foreach ($errors->all() as $error) 
                        <li>{{ $error }}</li> 
                        @endforeach 
                </ul> 
            </div> 
            @endif 
            <form action="{{ route('pinjams.store') }}" method="post"> 
                @csrf
        <div class="mb-3">
            <label class="form-label">Kode Peminjaman</label>
            <input type="text" class="form-control" name="kode_pinjam">
        </div>
        <div class="mb-3">
            <label class="form-label">Nama Anggota</label>
            <input type="text" class="form-control" name="nama_anggota">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Pinjam</label>
            <input type="date" class="form-control" name="tanggal_pinjam">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Kembali</label>
            <input type="date" class="form-control" name="tanggal_kembali">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    @include('layout/footer')

putraApp/resources/views/pinjams/edit.blade.php
@include('layout/header', ['title' => 'Form Data Peminjaman']) 
    <div class="container pt-4 bg-white">
    <h2>Form Peminjaman Buku</h2>
    @if ($errors->any()) 
            <div class="alert alert-danger"> 
                <ul> 
                    @foreach ($errors->all() as $error) 
                        <li>{{ $error }}</li> 
                        @endforeach 
                </ul> 
            </div> 
            @endif 
            <form action="{{ route('pinjams.update', $pinjam->id) }}" method="post"> 
                @csrf
                @method('PUT')
        <div class="mb-3">
            <label class="form-label">Kode Peminjaman</label>
            <input type="text" class="form-control" name="kode_pinjam" value="{{ $pinjam->kode_pinjam }}" readonly>
        </div>
        <div class="mb-3">
            <label class="form-label">Nama Anggota</label>
            <input type="text" class="form-control" name="nama_anggota">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Pinjam</label>
            <input type="date" class="form-control" name="tanggal_pinjam">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Kembali</label>
            <input type="date" class="form-control" name="tanggal_kembali">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    @include('layout/footer')

putraApp/resources/views/pinjams/index.blade.php
@include('layout/header', ['title' => 'Data Peminjaman'])   
<div class="container pt-4 bg-white">

        <h2>Data Peminjaman Buku</h2>
        <a href = "{{route('pinjams.create')}}" class="btn btn-info">Create</a>

        @include('flash-message')

        <table class="table table-hover">
            <tr>
                <th>Kode Peminjaman</th>
                <th>Nama Anggota</th>
                <th>Tanggal Pinjam</th>
                <th>Tanggal Kembali</th>
                <th>Action</th>
            </tr>
            @foreach ($pinjams as $pinjam)
            <tr>
                <td>{{ $pinjam->kode_pinjam }}</td>
                <td>{{ $pinjam->nama_anggota }}</td>
                <td>{{ $pinjam->tanggal_pinjam }}</td>
                <td>{{ $pinjam->tanggal_kembali }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                        <form action="{{ route('pinjams.destroy', [$pinjam]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{ route('pinjams.edit', [$pinjam]) }}" class="btn btn-primary">Edit</a>
                            <button class="btn btn-primary">Delete</button>
                        </form>
                        </div>
                    </td>
                </tr>
            @endforeach
        </table>
</div>
@include('layout/footer')