putraApp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\bookController;
use App\Http\Controllers\pinjamController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\pengembalianController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/dashboard', function () {
    return view('index');
});


Route::resource('books', bookController::class);

Route::resource('members', memberController::class);

Route::resource('pinjams',pinjamController::class);

Route::resource('pengembalians', pengembalianController::class);

Route::resource('posts', PostController::class);

putraApp/resources/views/layout/footer.blade.php
<footer class="bg-dark py-3 text-white mt-auto">
    <div class="container-fluid text-center">
        Sistem Informasi Perpustakaan | Copyright {{date("Y")}} Furuta
    </div>
</footer>
</body>
</html>

putraApp/resources/views/layout/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{{$title}}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body class="d-flex flex-column min-vh-100">
    <nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="">Perpustakaan</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link" href={{route('books.index')}}>Buku</a>
            <a class="nav-item nav-link" href="{{route('members.index')}}">Member</a>
            <a class="nav-item nav-link" href="{{route('pinjams.index')}}">Pinjam</a>
            <a class="nav-item nav-link" href="{{route('pengembalians.index')}}">Pengembalian</a>
          </div>
        </div>
      </nav>