putraApp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\bookController;
use App\Http\Controllers\pinjamController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\pengembalianController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/dashboard', function () {
    return view('index');
});


Route::resource('books', bookController::class);

Route::resource('members', memberController::class);

Route::resource('pinjams',pinjamController::class);

Route::resource('pengembalians', pengembalianController::class);

Route::resource('posts', PostController::class);

putraApp/app/Models/member.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class member extends Model
{
    use HasFactory;
    protected $fillable = ['kode_anggota','nama_anggota', 'KTP','Email','nomor_telepon','tanggal_daftar'];
}

putraApp/app/Http/Controllers/memberController.php
<?php

namespace App\Http\Controllers;

use App\Models\member;
use Illuminate\Http\Request;

class memberController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $members = member::all();
        return view('members.index', ['members' => $members]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('members.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //validasi
        $validated = $request->validate([
            'kode_anggota' => 'required',
            'nama_anggota' => 'required',
            'KTP' => 'required',
            'Email' => 'required',
            'nomor_telepon' => 'required',
            'tanggal_daftar' => 'required',
        ]);

        //simpan ke database
        $member = Member::create([
            'kode_anggota' => $request->input ('kode_anggota'),
            'nama_anggota' => $request->input ('nama_anggota'),
            'KTP' => $request->input ('KTP'),
            'Email' => $request->input ('Email'),
            'nomor_telepon' => $request->input ('nomor_telepon'),
            'tanggal_daftar' => $request->input ('tanggal_daftar'),
        ]);
        
        if($member){
            return redirect()->route('members.index')->with('success','Buku Berhasil Disimpan');
        }
        else{
            return redirect()->back()->with('error','Buku Gagal Disimpan');
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(member $member)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $member = member::find($id);

        return view('members.edit', ['member' => $member]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, member $member)
    {
        $validated = $request->validate([
            'kode_anggota' => 'required',
            'nama_anggota' => 'required',
            'KTP' => 'required',
            'Email' => 'required',
            'nomor_telepon' => 'required',
            'tanggal_daftar' => 'required',
        ]);

        $member->update([
            'kode_anggota' => $request->input('kode_anggota'),
            'nama_anggota' => $request->input('nama_anggota'),
            'KTP' => $request->input('KTP'),
            'Email' => $request->input('Email'),
            'nomor_telepon' => $request->input('nomor_telepon'),
            'tanggal_daftar' => $request->input('tanggal_daftar'),
        ]);

        if ($member) {
            return redirect()->route('members.index')->with('success', 'Data Anggota Berhasil Diperbarui');
        } else {
            return redirect()->back()->with('error', 'Data Anggota Gagal Diperbarui');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
        $member = member::destroy($id);
        $members = member::all();   
        return view('members.index', ['members' => $members]);
    }
}

putraApp/resources/views/members/create.blade.php
@include('layout/header', ['title' => 'Form Data Anggota'])  
    <div class="container pt-4 bg-white">
    <h2>Form Pendaftaran Anggota</h2>
    @if ($errors->any()) 
            <div class="alert alert-danger"> 
                <ul> 
                    @foreach ($errors->all() as $error) 
                        <li>{{ $error }}</li> 
                        @endforeach 
                </ul> 
            </div> 
            @endif 
            <form action="{{ route('members.store') }}" method="post"> 
                @csrf
        <div class="mb-3">
            <label class="form-label">Kode Anggota</label>
            <input type="text" class="form-control" name="kode_anggota">
        </div>
        <div class="mb-3">
            <label class="form-label">Nama Lengkap</label>
            <input type="text" class="form-control" name="nama_anggota">
        </div>
        <div class="mb-3">
            <label class="form-label">No KTP</label>
            <input type="number" class="form-control" name="KTP">
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="email" class="form-control" name="Email">
        </div>
        <div class="mb-3">
            <label class="form-label">Nomor Telepon</label>
            <input type="number" class="form-control" name="nomor_telepon">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Daftar</label>
            <input type="date" class="form-control" name="tanggal_daftar">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    @include('layout/footer')

putraApp/resources/views/members/edit.blade.php
@include('layout/header', ['title' => 'Edit Data Anggota'])  
    <div class="container pt-4 bg-white">
    <h2>Form Pendaftaran Anggota</h2>
    @if ($errors->any()) 
            <div class="alert alert-danger"> 
                <ul> 
                    @foreach ($errors->all() as $error) 
                        <li>{{ $error }}</li> 
                        @endforeach 
                </ul> 
            </div> 
            @endif 
            <form action="{{ route('members.update' , $member->id) }}" method="post"> 
                @csrf 
                @method('PUT')
        <div class="mb-3">
            <label class="form-label">Kode Anggota</label>
            <input type="text" class="form-control" name="kode_anggota" value="{{ $member->kode_anggota }}" readonly>
        </div>
        <div class="mb-3">
            <label class="form-label">Nama Lengkap</label>
            <input type="text" class="form-control" name="nama_anggota">
        </div>
        <div class="mb-3">
            <label class="form-label">No KTP</label>
            <input type="number" class="form-control" name="KTP">
        </div>
        <div class="mb-3">
            <label class="form-label">Email</label>
            <input type="email" class="form-control" name="Email">
        </div>
        <div class="mb-3">
            <label class="form-label">Nomor Telepon</label>
            <input type="number" class="form-control" name="nomor_telepon">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Daftar</label>
            <input type="date" class="form-control" name="tanggal_daftar">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    @include('layout/footer')

putraApp/resources/views/members/index.blade.php
@include('layout/header', ['title' => 'Data Anggota'])   
<div class="container pt-4 bg-white">
        <h2>Data Anggota Perpustakaan</h2>
        <a href = "{{route('members.create')}}" class="btn btn-info">Create</a>
        @include('flash-message')
        <table class="table table-hover">
            <tr>
                <th>Kode Anggota</th>
                <th>Nama Anggota</th>
                <th>KTP</th>
                <th>Email</th>
                <th>No Telepon</th>
                <th>Tanggal Daftar</th>
                <th>Action</th>
            </tr>

            @foreach ($members as $member )   
                <tr>
                    <td>{{ $member->kode_anggota }}</td>
                    <td>{{ $member->nama_anggota }}</td>
                    <td>{{ $member->KTP }}</td>
                    <td>{{ $member->Email }}</td>
                    <td>{{ $member->nomor_telepon }}</td>
                    <td>{{ $member->tanggal_daftar }}</td>
                    <td>
                        <div class="btn-group" role="group" aria-label="Basic example">
                        <form action="{{ route('members.destroy', [$member]) }}" method="POST">
                            @csrf
                            @method('DELETE')
                            <a href="{{ route('members.edit', [$member]) }}" class="btn btn-primary">Edit</a>
                            <button class="btn btn-primary">Delete</button>
                        </form>
                        </div>
                    </td>
                </tr>
                @endforeach
        </table>
</div>
@include('layout/footer')