putraApp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\bookController;
use App\Http\Controllers\pinjamController;
use App\Http\Controllers\memberController;
use App\Http\Controllers\pengembalianController;
use App\Http\Controllers\PostController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('/dashboard', function () {
    return view('index');
});


Route::resource('books', bookController::class);

Route::resource('members', memberController::class);

Route::resource('pinjams',pinjamController::class);

Route::resource('pengembalians', pengembalianController::class);

Route::resource('posts', PostController::class);

putraApp/app/Models/pengembalian.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class pengembalian extends Model
{
    use HasFactory;
    protected $fillable = ['kode_pengembalian','tanggal_pinjam','tanggal_kembali','keterlambatan','denda'];
}

putraApp/app/Http/Controllers/pengembalianController.php
<?php

namespace App\Http\Controllers;

use App\Models\pengembalian;
use Illuminate\Http\Request;

class pengembalianController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $pengembalians = pengembalian::all();
        return view('pengembalians.index', ['pengembalians' => $pengembalians]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view ('pengembalians.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'kode_pengembalian' => 'required',
            'tanggal_kembali' => 'required',
            'tanggal_pinjam' => 'required',
            'keterlambatan' => 'required',
            'denda' => 'required',
        ]);

        //simpan ke database
        $pengembalian = Pengembalian::create([
            'kode_pengembalian' => $request->input ('kode_pengembalian'),
            'tanggal_kembali' => $request->input ('tanggal_kembali'),
            'tanggal_pinjam' => $request->input ('tanggal_pinjam'),
            'keterlambatan' => $request->input ('keterlambatan'),
            'denda' => $request->input ('denda'),
        ]);

        //flash message
        if($pengembalian){
            return redirect()->route('pengembalians.index')->with('success','Data Berhasil Disimpan');
        }
        else{
            return redirect()->back()->with('error','Data Gagal Disimpan');
        }
    }


    /**
     * Display the specified resource.
     */
    public function show(pengembalian $pengembalian)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit($id)
    {
        $pengembalian = pengembalian::find($id);
        return view('pengembalians.edit', ['pengembalian' => $pengembalian]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, pengembalian $pengembalian)
    {
        $validated = $request->validate([
            'kode_pengembalian' => 'required',
            'tanggal_kembali' => 'required',
            'tanggal_pinjam' => 'required',
            'keterlambatan' => 'required',
            'denda' => 'required',
        ]);

        //simpan ke database
        $pengembalian->update([
            'kode_pengembalian' => $request->input ('kode_pengembalian'),
            'tanggal_kembali' => $request->input ('tanggal_kembali'),
            'tanggal_pinjam' => $request->input ('tanggal_pinjam'),
            'keterlambatan' => $request->input ('keterlambatan'),
            'denda' => $request->input ('denda'),
        ]);

        //flash message
        if($pengembalian){
            return redirect()->route('pengembalians.index')->with('success','Data Berhasil Diperbarui');
        }
        else{
            return redirect()->back()->with('error','Data Gagal Diperbarui');
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy($id)
    {
    
        $pengembalians = pengembalian::destroy($id);
        $pengembalians = pengembalian::all();   
        return view('pengembalians.index', ['pengembalians' => $pengembalians]);
    }
}

putraApp/resources/views/pengembalians/create.blade.php
@include('layout/header', ['title' => 'Form Data Pengembalian'])  
    <div class="container pt-4 bg-white">
    <h2>Form Pengembalian Buku</h2>
    @if ($errors->any()) 
            <div class="alert alert-danger"> 
                <ul> 
                    @foreach ($errors->all() as $error) 
                        <li>{{ $error }}</li> 
                        @endforeach 
                </ul> 
            </div> 
            @endif 
            <form action="{{ route('pengembalians.store') }}" method="post"> 
                @csrf
        <div class="mb-3">
            <label class="form-label">Kode_Pengembalian</label>
            <input type="text" class="form-control" name="kode_pengembalian">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Pinjam</label>
            <input type="date" class="form-control" name="tanggal_pinjam">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Kembali</label>
            <input type="date" class="form-control" name="tanggal_kembali">
        </div>
        <div class="mb-3">
            <label class="form-label">Periode</label>
            <select name="keterlambatan" class="form-control">
              <option>Keterlambatan</option>
              <option value="Terlambat">Terlambat</option>
              <option value="Tepat Waktu">Tepat Waktu</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Denda</label>
            <input type="text" class="form-control" name="denda">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    @include('layout/footer')

putraApp/resources/views/pengembalians/edit.blade.php
@include('layout/header', ['title' => 'Data Edit Pengembalian'])  
    <div class="container pt-4 bg-white">
    <h2>Form Pengembalian Buku</h2>
    @if ($errors->any()) 
            <div class="alert alert-danger"> 
                <ul> 
                    @foreach ($errors->all() as $error) 
                        <li>{{ $error }}</li> 
                        @endforeach 
                </ul> 
            </div> 
            @endif 
            <form action="{{ route('pengembalians.update', $pengembalian->id) }}" method="post"> 
                @csrf
                @method('PUT')
        <div class="mb-3">
            <label class="form-label">Kode_Pengembalian</label>
            <input type="text" class="form-control" name="kode_pengembalian" value="{{ $pengembalian->kode_pengembalian }}" readonly>
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Pinjam</label>
            <input type="date" class="form-control" name="tanggal_pinjam">
        </div>
        <div class="mb-3">
            <label class="form-label">Tanggal Kembali</label>
            <input type="date" class="form-control" name="tanggal_kembali">
        </div>
        <div class="mb-3">
            <label class="form-label">Periode</label>
            <select name="keterlambatan" class="form-control">
              <option>Keterlambatan</option>
              <option value="Terlambat">Terlambat</option>
              <option value="Tepat Waktu">Tepat Waktu</option>
            </select>
        </div>
        <div class="mb-3">
            <label class="form-label">Denda</label>
            <input type="text" class="form-control" name="denda">
        </div>
        <button type="submit" class="btn btn-primary">Simpan</button>
        </form>
    </div>
    @include('layout/footer')

putraApp/resources/views/pengembalians/index.blade.php
@include('layout/header', ['title' => 'Data Pengembalian'])  
<div class="container pt-4 bg-white">
        <h2>Data Pengembalian Buku</h2>
        <table class="table table-hover">
        <a href = "{{route('pengembalians.create')}}" class="btn btn-info">Create</a>
        @include('flash-message')
            <tr>
                <th>Kode Pengembalian</th>
                <th>Tanggal Pinjam</th>
                <th>Tanggal Kembali</th>
                <th>Keterlambatan</th>
                <th>Denda</th>
                <th>Action</th>
            </tr>
            @foreach ($pengembalians as $pengembalian)
            <tr>
                <td>{{ $pengembalian->kode_pengembalian }}</td>
                <td>{{ $pengembalian->tanggal_pinjam }}</td>
                <td>{{ $pengembalian->tanggal_kembali }}</td>
                <td>{{ $pengembalian->keterlambatan }}</td>
                <td>{{ $pengembalian->denda }}</td>
                <td>
                    <div class="btn-group" role="group" aria-label="Basic example">
                    <form action="{{ route('pengembalians.destroy', [$pengembalian]) }}" method="POST">
                        @csrf
                        @method('DELETE')
                        <a href="{{ route('pengembalians.edit', [$pengembalian]) }}" class="btn btn-primary">Edit</a>
                        <button class="btn btn-primary">Delete</button>
                    </form>
                    </div>
                </td>
            </tr>
        @endforeach
    </table>
</div>
    @include('layout/footer')